# Generated by Django 5.1.6 on 2025-03-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
