# Generated by Django 5.1.6 on 2025-03-09 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10-15 digits.', regex='^\\d{10,15}$')])),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('total_purchase', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('WholeSale', 'WholeSale'), ('Retail', 'Retail'), ('Distributor', 'Distributor')], default='Retail', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
