# Generated by Django 5.1.6 on 2025-03-09 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_seller'),
        ('order', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_status',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Online', 'Online')], default='Card', max_length=50),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('debit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.shipment')),
            ],
        ),
    ]
