# Generated by Django 5.1.6 on 2025-03-09 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_seller'),
        ('payment', '0002_remove_shipment_shipment_status_and_more'),
        ('store', '0002_customer_user_id_seller_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='record',
            name='order',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user_id',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('size_type', models.CharField(choices=[('lb', 'Pound'), ('onz', 'Ounce')], max_length=10)),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Food', 'Food'), ('Furniture', 'Furniture')], default='Food', max_length=50)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.seller')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
